services:
  xray-balancer-mw:
    build: .
    container_name: xray-balancer-mw
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CONFIG_RUNTIME_PATH=/app/runtime/config.runtime.json
    volumes:
      - ./config.json:/app/config.json:ro
      - xray-balancer-runtime:/app/runtime
    networks:
      - remnawave-network

networks:
  remnawave-network:
    external: true
    name: remnawave-network

volumes:
  xray-balancer-runtime:
