services:
  xray-balancer-mw:
    build: ../
    container_name: xray-balancer-mw
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - CONFIG_RUNTIME_PATH=/app/runtime/config.runtime.json
    volumes:
      - ../config.json:/app/config.json:ro
      - xray-balancer-runtime:/app/runtime
    networks:
      - remnawave-network

  nginx:
    image: nginx:alpine
    container_name: nginx-remnawave
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    networks:
      - remnawave-network
    depends_on:
      - xray-balancer-mw

networks:
  remnawave-network:
    external: true
    name: remnawave-network

volumes:
  xray-balancer-runtime:
